name: test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  run-tests:
    strategy: 
      fail-fast: false
      matrix: 
        os: [ubuntu-20.04, ubuntu-22.04]
        python-version: 
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    name: Test
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
        
      - name: Create conda environment with mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          auto-activate-base: false
          activate-environment: titanic-env
          environment-file: envs/environment.yml
        
      - name: Install pytest
        run: python -m pip install pytest .

      - name: Run tests
        run: |
          uname -a
          which python
          
          pytest

          