name: test

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  run-tests:
    defaults:
      run:
        shell: bash -l {0}
    strategy: 
      fail-fast: false
      matrix: 
        os: [ubuntu-22.04, ubuntu-20.04]
        python-version: 
          - "3.9"
          - "3.10"
          - "3.11"
    name: Test
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}
                
      - name: Install pytest
        run: python -m pip install -r tests/requirements.txt

      - name: Run tests
        run: |
          uname -a
          which python
          
          pytest

          